//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IT_inventory_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class AD_Users
    {
        public int EDMXID { get; set; }
        public string sAMAccountName { get; set; }
        public string sn { get; set; }
        public string cn { get; set; }
        public string givenName { get; set; }
        public string title { get; set; }
        public string displayName { get; set; }
        public string physicalDeliveryOfficeName { get; set; }
        public byte[] objectGUID { get; set; }
        public byte[] objectSid { get; set; }
    }
}
