//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IT_inventory_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TE_Gepek
    {
        public int nid { get; set; }
        public string Computer_name { get; set; }
        public string Device_manufacturer { get; set; }
        public string Device_model { get; set; }
        public string Serial_number { get; set; }
    }
}
