//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IT_inventory_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TE_Helysegek
    {
        public string Helyseg_Azon { get; set; }
        public string Helyseg_Nev { get; set; }
    }
}
