//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IT_inventory_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TE_Leltar
    {
        public int nid { get; set; }
        public string Nev { get; set; }
        public string Hely { get; set; }
        public string Felhasznalo { get; set; }
        public string Csoport { get; set; }
        public string Statusz { get; set; }
        public string Tipusok { get; set; }
        public string Gyarto { get; set; }
        public string Modell { get; set; }
        public string Sorozatszam { get; set; }
        public string Leltari_Szam { get; set; }
    }
}
